"""
All training exercises organized by SQL operator category.
Each exercise has:
  id          - unique int
  category    - display name of the operator group
  min_tables  - minimum number of tables required (1=users, 2=+orders, 3=+products, 4=+returns, 5=+service_requests)
  description - task shown to the user
  hint        - operator hint (hidden behind a button in the UI)
  solution    - correct SQL answer
  check_order - True if row order matters (ORDER BY exercises)
  needs_reset - True for INSERT/UPDATE/DELETE (DB is reset before each attempt)
  verify_query         - SELECT used to verify DML result
  verify_expected_count - expected COUNT(*) from verify_query after DML
"""

EXERCISES_LIST = [

    # =========================================================
    # CATEGORY 1: SELECT / FROM / WHERE / ORDER BY / LIMIT
    # =========================================================
    {
        'id': 1,
        'category': 'SELECT / WHERE / ORDER BY / LIMIT',
        'hint': 'SELECT *',
        'min_tables': 1,
        'description': 'Select <b>all data</b> from the <b>users</b> table.',
        'solution': 'SELECT * FROM users',
        'check_order': False,
    },
    {
        'id': 2,
        'category': 'SELECT / WHERE / ORDER BY / LIMIT',
        'hint': 'SELECT col1, col2',
        'min_tables': 1,
        'description': 'Select only the <b>name</b> and <b>email</b> columns of all users.',
        'solution': 'SELECT name, email FROM users',
        'check_order': False,
    },
    {
        'id': 3,
        'category': 'SELECT / WHERE / ORDER BY / LIMIT',
        'hint': 'WHERE >',
        'min_tables': 1,
        'description': 'Select all users whose <b>age</b> is greater than <b>30</b>.',
        'solution': 'SELECT * FROM users WHERE age > 30',
        'check_order': False,
    },
    {
        'id': 4,
        'category': 'SELECT / WHERE / ORDER BY / LIMIT',
        'hint': "WHERE =",
        'min_tables': 1,
        'description': "Select all users from the city <code>'Moscow'</code>.",
        'solution': "SELECT * FROM users WHERE city = 'Moscow'",
        'check_order': False,
    },
    {
        'id': 5,
        'category': 'SELECT / WHERE / ORDER BY / LIMIT',
        'hint': 'ORDER BY DESC',
        'min_tables': 1,
        'description': 'Select all users sorted by <b>age</b> from <b>oldest to youngest</b>.',
        'solution': 'SELECT * FROM users ORDER BY age DESC',
        'check_order': True,
    },
    {
        'id': 6,
        'category': 'SELECT / WHERE / ORDER BY / LIMIT',
        'hint': 'ORDER BY + LIMIT',
        'min_tables': 1,
        'description': 'Select the <b>5 most recently registered</b> users (by <b>registered_at</b>), newest first.',
        'solution': 'SELECT * FROM users ORDER BY registered_at DESC LIMIT 5',
        'check_order': True,
    },
    {
        'id': 7,
        'category': 'SELECT / WHERE / ORDER BY / LIMIT',
        'hint': 'WHERE + SELECT cols',
        'min_tables': 1,
        'description': 'Select the <b>name</b> and <b>city</b> of <b>active users only</b> (<b>is_active = 1</b>).',
        'solution': 'SELECT name, city FROM users WHERE is_active = 1',
        'check_order': False,
    },
    {
        'id': 8,
        'category': 'SELECT / WHERE / ORDER BY / LIMIT',
        'hint': 'WHERE + ORDER BY DESC',
        'min_tables': 2,
        'description': "Select all <b>delivered</b> orders (<code>status = 'delivered'</code>), sorted by <b>ordered_at</b> newest first.",
        'solution': "SELECT * FROM orders WHERE status = 'delivered' ORDER BY ordered_at DESC",
        'check_order': True,
    },
    {
        'id': 9,
        'category': 'SELECT / WHERE / ORDER BY / LIMIT',
        'hint': 'ORDER BY + LIMIT',
        'min_tables': 2,
        'description': 'Select the <b>top 3 most expensive orders</b> by <b>total_price</b>.',
        'solution': 'SELECT * FROM orders ORDER BY total_price DESC LIMIT 3',
        'check_order': True,
    },
    {
        'id': 10,
        'category': 'SELECT / WHERE / ORDER BY / LIMIT',
        'hint': 'WHERE + ORDER BY ASC',
        'min_tables': 3,
        'description': "Select the <b>name</b> and <b>price</b> of products in the <code>'Electronics'</code> category, sorted by price <b>ascending</b>.",
        'solution': "SELECT name, price FROM products WHERE category = 'Electronics' ORDER BY price ASC",
        'check_order': True,
    },

    # =========================================================
    # CATEGORY 2: Filtering
    # =========================================================
    {
        'id': 11,
        'category': 'Filtering',
        'hint': 'AND',
        'min_tables': 1,
        'description': 'Select active users (<b>is_active = 1</b>) who are older than <b>25</b>.',
        'solution': 'SELECT * FROM users WHERE is_active = 1 AND age > 25',
        'check_order': False,
    },
    {
        'id': 12,
        'category': 'Filtering',
        'hint': 'OR',
        'min_tables': 1,
        'description': "Select users from <code>'Moscow'</code> or <code>'London'</code>.",
        'solution': "SELECT * FROM users WHERE city = 'Moscow' OR city = 'London'",
        'check_order': False,
    },
    {
        'id': 13,
        'category': 'Filtering',
        'hint': 'IN',
        'min_tables': 1,
        'description': "Select users from the cities <code>'Moscow'</code>, <code>'Paris'</code>, or <code>'Berlin'</code>.",
        'solution': "SELECT * FROM users WHERE city IN ('Moscow', 'Paris', 'Berlin')",
        'check_order': False,
    },
    {
        'id': 14,
        'category': 'Filtering',
        'hint': 'NOT IN',
        'min_tables': 1,
        'description': "Select users who are <b>not</b> from <code>'Moscow'</code> or <code>'London'</code>.",
        'solution': "SELECT * FROM users WHERE city NOT IN ('Moscow', 'London')",
        'check_order': False,
    },
    {
        'id': 15,
        'category': 'Filtering',
        'hint': 'LIKE',
        'min_tables': 1,
        'description': "Select users whose <b>name</b> starts with the letter <code>'A'</code>.",
        'solution': "SELECT * FROM users WHERE name LIKE 'A%'",
        'check_order': False,
    },
    {
        'id': 16,
        'category': 'Filtering',
        'hint': 'NOT LIKE',
        'min_tables': 1,
        'description': "Select users whose <b>email</b> does <b>not</b> contain <code>'gmail'</code>.",
        'solution': "SELECT * FROM users WHERE email NOT LIKE '%gmail%'",
        'check_order': False,
    },
    {
        'id': 17,
        'category': 'Filtering',
        'hint': 'BETWEEN',
        'min_tables': 1,
        'description': 'Select users aged between <b>25</b> and <b>35</b> inclusive.',
        'solution': 'SELECT * FROM users WHERE age BETWEEN 25 AND 35',
        'check_order': False,
    },
    {
        'id': 18,
        'category': 'Filtering',
        'hint': 'NOT BETWEEN',
        'min_tables': 1,
        'description': "Select users who registered <b>outside of 2023</b> — not between <code>'2023-01-01'</code> and <code>'2023-12-31'</code>.",
        'solution': "SELECT * FROM users WHERE registered_at NOT BETWEEN '2023-01-01' AND '2023-12-31'",
        'check_order': False,
    },
    {
        'id': 19,
        'category': 'Filtering',
        'hint': 'IS NULL',
        'min_tables': 1,
        'description': 'Select users who have <b>no phone number</b> on record.',
        'solution': 'SELECT * FROM users WHERE phone IS NULL',
        'check_order': False,
    },
    {
        'id': 20,
        'category': 'Filtering',
        'hint': 'IS NOT NULL',
        'min_tables': 1,
        'description': 'Select users who <b>have</b> a phone number on record.',
        'solution': 'SELECT * FROM users WHERE phone IS NOT NULL',
        'check_order': False,
    },

    # =========================================================
    # CATEGORY 3: Aggregate Functions
    # =========================================================
    {
        'id': 21,
        'category': 'Aggregate Functions',
        'hint': 'COUNT(*)',
        'min_tables': 1,
        'description': 'Count the <b>total number of users</b> in the <b>users</b> table.',
        'solution': 'SELECT COUNT(*) FROM users',
        'check_order': False,
    },
    {
        'id': 22,
        'category': 'Aggregate Functions',
        'hint': 'COUNT(DISTINCT)',
        'min_tables': 1,
        'description': 'Count the number of <b>unique cities</b> among all users.',
        'solution': 'SELECT COUNT(DISTINCT city) FROM users',
        'check_order': False,
    },
    {
        'id': 23,
        'category': 'Aggregate Functions',
        'hint': 'AVG()',
        'min_tables': 1,
        'description': 'Find the <b>average age</b> of all users.',
        'solution': 'SELECT AVG(age) FROM users',
        'check_order': False,
    },
    {
        'id': 24,
        'category': 'Aggregate Functions',
        'hint': 'MIN() / MAX()',
        'min_tables': 1,
        'description': 'Find the <b>minimum</b> and <b>maximum</b> age among all users — both values in a single query.',
        'solution': 'SELECT MIN(age), MAX(age) FROM users',
        'check_order': False,
    },
    {
        'id': 25,
        'category': 'Aggregate Functions',
        'hint': 'COUNT(*)',
        'min_tables': 2,
        'description': 'Count the <b>total number of orders</b> in the <b>orders</b> table.',
        'solution': 'SELECT COUNT(*) FROM orders',
        'check_order': False,
    },
    {
        'id': 26,
        'category': 'Aggregate Functions',
        'hint': 'SUM()',
        'min_tables': 2,
        'description': 'Find the <b>total sum</b> of all orders (<b>total_price</b>).',
        'solution': 'SELECT SUM(total_price) FROM orders',
        'check_order': False,
    },
    {
        'id': 27,
        'category': 'Aggregate Functions',
        'hint': 'AVG()',
        'min_tables': 2,
        'description': 'Find the <b>average cost</b> of an order (<b>total_price</b>).',
        'solution': 'SELECT AVG(total_price) FROM orders',
        'check_order': False,
    },
    {
        'id': 28,
        'category': 'Aggregate Functions',
        'hint': 'MAX()',
        'min_tables': 2,
        'description': 'Find the <b>most expensive</b> single order (<b>MAX total_price</b>).',
        'solution': 'SELECT MAX(total_price) FROM orders',
        'check_order': False,
    },
    {
        'id': 29,
        'category': 'Aggregate Functions',
        'hint': 'AVG() + WHERE',
        'min_tables': 3,
        'description': "Find the <b>average price</b> of products in the <code>'Electronics'</code> category.",
        'solution': "SELECT AVG(price) FROM products WHERE category = 'Electronics'",
        'check_order': False,
    },
    {
        'id': 30,
        'category': 'Aggregate Functions',
        'hint': 'SUM(expr)',
        'min_tables': 3,
        'description': 'Calculate the <b>total inventory value</b> — the sum of <b>price × stock</b> across all products.',
        'solution': 'SELECT SUM(price * stock) FROM products',
        'check_order': False,
    },

    # =========================================================
    # CATEGORY 4: GROUP BY / HAVING
    # =========================================================
    {
        'id': 31,
        'category': 'GROUP BY / HAVING',
        'hint': 'GROUP BY',
        'min_tables': 1,
        'description': 'Count the number of users in each <b>city</b>. Show city and count.',
        'solution': 'SELECT city, COUNT(*) FROM users GROUP BY city',
        'check_order': False,
    },
    {
        'id': 32,
        'category': 'GROUP BY / HAVING',
        'hint': 'GROUP BY + AVG',
        'min_tables': 1,
        'description': 'Find the <b>average age</b> of users in each city. Show city and average age.',
        'solution': 'SELECT city, AVG(age) FROM users GROUP BY city',
        'check_order': False,
    },
    {
        'id': 33,
        'category': 'GROUP BY / HAVING',
        'hint': 'GROUP BY + HAVING',
        'min_tables': 1,
        'description': 'Show only the cities where <b>more than 2</b> users are registered.',
        'solution': 'SELECT city, COUNT(*) FROM users GROUP BY city HAVING COUNT(*) > 2',
        'check_order': False,
    },
    {
        'id': 34,
        'category': 'GROUP BY / HAVING',
        'hint': 'GROUP BY',
        'min_tables': 2,
        'description': 'Count the number of orders for each <b>status</b>. Show status and count.',
        'solution': 'SELECT status, COUNT(*) FROM orders GROUP BY status',
        'check_order': False,
    },
    {
        'id': 35,
        'category': 'GROUP BY / HAVING',
        'hint': 'GROUP BY + SUM',
        'min_tables': 2,
        'description': 'Find the <b>total order amount</b> per user. Show <b>user_id</b> and sum.',
        'solution': 'SELECT user_id, SUM(total_price) FROM orders GROUP BY user_id',
        'check_order': False,
    },
    {
        'id': 36,
        'category': 'GROUP BY / HAVING',
        'hint': 'GROUP BY + HAVING SUM',
        'min_tables': 2,
        'description': 'Show the <b>user_id</b> of users whose total order amount <b>exceeds 100</b>.',
        'solution': 'SELECT user_id, SUM(total_price) FROM orders GROUP BY user_id HAVING SUM(total_price) > 100',
        'check_order': False,
    },
    {
        'id': 37,
        'category': 'GROUP BY / HAVING',
        'hint': 'GROUP BY + COUNT',
        'min_tables': 3,
        'description': 'Count the number of products in each <b>category</b>. Show category and count.',
        'solution': 'SELECT category, COUNT(*) FROM products GROUP BY category',
        'check_order': False,
    },
    {
        'id': 38,
        'category': 'GROUP BY / HAVING',
        'hint': 'GROUP BY + HAVING AVG',
        'min_tables': 3,
        'description': 'Find the average price per category. Show only categories where the average price is <b>greater than 50</b>.',
        'solution': 'SELECT category, AVG(price) FROM products GROUP BY category HAVING AVG(price) > 50',
        'check_order': False,
    },
    {
        'id': 39,
        'category': 'GROUP BY / HAVING',
        'hint': 'GROUP BY + MAX',
        'min_tables': 2,
        'description': 'Find the <b>maximum order amount</b> for each status. Show status and max.',
        'solution': 'SELECT status, MAX(total_price) FROM orders GROUP BY status',
        'check_order': False,
    },
    {
        'id': 40,
        'category': 'GROUP BY / HAVING',
        'hint': 'GROUP BY + HAVING COUNT',
        'min_tables': 3,
        'description': 'Show categories that have <b>more than 3</b> products.',
        'solution': 'SELECT category, COUNT(*) FROM products GROUP BY category HAVING COUNT(*) > 3',
        'check_order': False,
    },

    # =========================================================
    # CATEGORY 5: JOIN / LEFT JOIN
    # =========================================================
    {
        'id': 41,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN',
        'min_tables': 2,
        'description': "Show each user's <b>name (users.name)</b> and their <b>order amount (orders.total_price)</b> for all orders.",
        'solution': 'SELECT users.name, orders.total_price FROM users JOIN orders ON users.id = orders.user_id',
        'check_order': False,
    },
    {
        'id': 42,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN',
        'min_tables': 2,
        'description': "Show every user's <b>name (users.name)</b> and their <b>order id (orders.id)</b>. Include users who have <b>no orders</b>.",
        'solution': 'SELECT users.name, orders.id FROM users LEFT JOIN orders ON users.id = orders.user_id',
        'check_order': False,
    },
    {
        'id': 43,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + WHERE',
        'min_tables': 2,
        'description': "Show the <b>user's name (users.name)</b> and <b>order status (orders.status)</b>, but only for orders with status <code>'delivered'</code>.",
        'solution': "SELECT users.name, orders.status FROM users JOIN orders ON users.id = orders.user_id WHERE orders.status = 'delivered'",
        'check_order': False,
    },
    {
        'id': 44,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + JOIN',
        'min_tables': 3,
        'description': "Show the <b>user's name (users.name)</b>, <b>product name (products.name)</b>, and <b>quantity (orders.quantity)</b>. Join all three tables.",
        'solution': 'SELECT users.name, products.name, orders.quantity FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id',
        'check_order': False,
    },
    {
        'id': 45,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN + GROUP BY',
        'min_tables': 3,
        'description': "Show each <b>product name (products.name)</b> and <b>how many times it was ordered</b>. Include products that were <b>never ordered</b>.",
        'solution': 'SELECT products.name, COUNT(orders.id) FROM products LEFT JOIN orders ON products.id = orders.product_id GROUP BY products.id, products.name',
        'check_order': False,
    },
    {
        'id': 46,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + GROUP BY',
        'min_tables': 3,
        'description': "Show each <b>user's name (users.name)</b> and their <b>total order amount</b>.",
        'solution': 'SELECT users.name, SUM(orders.total_price) FROM users JOIN orders ON users.id = orders.user_id GROUP BY users.id, users.name',
        'check_order': False,
    },
    {
        'id': 47,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 3 tables',
        'min_tables': 4,
        'description': "Show the <b>user's name (users.name)</b> and the <b>return reason (returns.reason)</b> for all returns. Join three tables.",
        'solution': 'SELECT users.name, returns.reason FROM users JOIN orders ON users.id = orders.user_id JOIN returns ON orders.id = returns.order_id',
        'check_order': False,
    },
    {
        'id': 48,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN',
        'min_tables': 4,
        'description': "Show <b>order id (orders.id)</b>, <b>total price</b>, and <b>return reason (returns.reason)</b>. Include orders <b>without returns</b>.",
        'solution': 'SELECT orders.id, orders.total_price, returns.reason FROM orders LEFT JOIN returns ON orders.id = returns.order_id',
        'check_order': False,
    },
    {
        'id': 49,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN',
        'min_tables': 5,
        'description': "Show the <b>user's name (users.name)</b> and the <b>ticket subject (service_requests.subject)</b> for all support tickets.",
        'solution': 'SELECT users.name, service_requests.subject FROM users JOIN service_requests ON users.id = service_requests.user_id',
        'check_order': False,
    },
    {
        'id': 50,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN',
        'min_tables': 5,
        'description': "Show <b>order id (orders.id)</b>, <b>status</b>, and the <b>ticket subject (service_requests.subject)</b>. Include orders <b>without tickets</b>.",
        'solution': 'SELECT orders.id, orders.status, service_requests.subject FROM orders LEFT JOIN service_requests ON orders.id = service_requests.order_id',
        'check_order': False,
    },

    # =========================================================
    # CATEGORY 6: Functions
    # =========================================================
    {
        'id': 51,
        'category': 'Functions',
        'hint': 'ROUND()',
        'min_tables': 2,
        'description': "Show each order's <b>id</b> and its <b>total_price</b> rounded to the <b>nearest integer</b>.",
        'solution': 'SELECT id, ROUND(total_price) FROM orders',
        'check_order': False,
    },
    {
        'id': 52,
        'category': 'Functions',
        'hint': 'ROUND(x, n)',
        'min_tables': 3,
        'description': "Show the <b>name</b> and <b>price</b> of each product rounded to <b>1 decimal place</b>.",
        'solution': 'SELECT name, ROUND(price, 1) FROM products',
        'check_order': False,
    },
    {
        'id': 53,
        'category': 'Functions',
        'hint': 'LOWER()',
        'min_tables': 1,
        'description': "Show the <b>email</b> of all users in <b>lowercase</b>.",
        'solution': 'SELECT LOWER(email) FROM users',
        'check_order': False,
    },
    {
        'id': 54,
        'category': 'Functions',
        'hint': '|| (concatenation)',
        'min_tables': 1,
        'description': "Combine each user's <b>name</b> and <b>city</b> into one string separated by <code>' - '</code>. Example: <code>Anna Smith - Moscow</code>.",
        'solution': "SELECT name || ' - ' || city FROM users",
        'check_order': False,
        'dialect_variants': {
            'mysql': {
                'hint': 'CONCAT()',
                'solution': "SELECT CONCAT(name, ' - ', city) FROM users",
            },
        },
    },
    {
        'id': 55,
        'category': 'Functions',
        'hint': 'COALESCE()',
        'min_tables': 1,
        'description': "Show each user's <b>name</b> and <b>phone</b>. If the phone is missing, show <code>'Not provided'</code> instead.",
        'solution': "SELECT name, COALESCE(phone, 'Not provided') FROM users",
        'check_order': False,
    },
    {
        'id': 56,
        'category': 'Functions',
        'hint': 'LOWER() + GROUP BY',
        'min_tables': 3,
        'description': "Show each product <b>category in lowercase</b> and the number of products in it.",
        'solution': 'SELECT LOWER(category), COUNT(*) FROM products GROUP BY category',
        'check_order': False,
    },
    {
        'id': 57,
        'category': 'Functions',
        'hint': 'ROUND() + AVG()',
        'min_tables': 2,
        'description': "Show the <b>average order cost</b> rounded to <b>2 decimal places</b>.",
        'solution': 'SELECT ROUND(AVG(total_price), 2) FROM orders',
        'check_order': False,
    },
    {
        'id': 58,
        'category': 'Functions',
        'hint': '|| (concatenation)',
        'min_tables': 2,
        'description': "Format each order as: <code>Order #&lt;id&gt;: &lt;status&gt;</code>. Example: <code>Order #1: delivered</code>.",
        'solution': "SELECT 'Order #' || id || ': ' || status FROM orders",
        'check_order': False,
        'dialect_variants': {
            'mysql': {
                'hint': 'CONCAT()',
                'solution': "SELECT CONCAT('Order #', id, ': ', status) FROM orders",
            },
        },
    },
    {
        'id': 59,
        'category': 'Functions',
        'hint': 'COALESCE()',
        'min_tables': 5,
        'description': "Show <b>user_id</b> and <b>order_id</b> from <b>service_requests</b>. If <b>order_id</b> is NULL, show <code>'General'</code>.",
        'solution': "SELECT user_id, COALESCE(CAST(order_id AS TEXT), 'General') FROM service_requests",
        'check_order': False,
        'dialect_variants': {
            'mysql': {
                'solution': "SELECT user_id, COALESCE(CAST(order_id AS CHAR), 'General') FROM service_requests",
            },
        },
    },
    {
        'id': 60,
        'category': 'Functions',
        'hint': 'ROUND(expr)',
        'min_tables': 3,
        'description': "Show each <b>product name</b> and its total inventory value (<b>price × stock</b>) rounded to the nearest integer.",
        'solution': 'SELECT name, ROUND(price * stock) FROM products',
        'check_order': False,
    },

    # =========================================================
    # CATEGORY 7: CASE WHEN
    # =========================================================
    {
        'id': 61,
        'category': 'CASE WHEN',
        'hint': 'CASE WHEN . ELSE',
        'min_tables': 1,
        'description': "Show each user's <b>name</b> and an activity label: if <b>is_active = 1</b> → <code>'Active'</code>, otherwise → <code>'Inactive'</code>. Name the column <b>status</b>.",
        'solution': "SELECT name, CASE WHEN is_active = 1 THEN 'Active' ELSE 'Inactive' END AS status FROM users",
        'check_order': False,
    },
    {
        'id': 62,
        'category': 'CASE WHEN',
        'hint': 'CASE WHEN . WHEN . ELSE',
        'min_tables': 1,
        'description': "Show each user's <b>name</b>, <b>age</b>, and age group: under 25 → <code>'Young'</code>, 25–40 → <code>'Middle'</code>, over 40 → <code>'Senior'</code>. Name the column <b>age_group</b>.",
        'solution': "SELECT name, age, CASE WHEN age < 25 THEN 'Young' WHEN age BETWEEN 25 AND 40 THEN 'Middle' ELSE 'Senior' END AS age_group FROM users",
        'check_order': False,
    },
    {
        'id': 63,
        'category': 'CASE WHEN',
        'hint': 'CASE WHEN . ELSE',
        'min_tables': 2,
        'description': "Show each order's <b>id</b>, <b>total_price</b>, and size label: if total_price > 100 → <code>'Large'</code>, otherwise → <code>'Small'</code>. Name the column <b>order_size</b>.",
        'solution': "SELECT id, total_price, CASE WHEN total_price > 100 THEN 'Large' ELSE 'Small' END AS order_size FROM orders",
        'check_order': False,
    },
    {
        'id': 64,
        'category': 'CASE WHEN',
        'hint': 'CASE WHEN multi-value',
        'min_tables': 2,
        'description': "Show each order's <b>id</b> and translate its status: <code>'delivered'</code> → <code>'Delivered'</code>, <code>'cancelled'</code> → <code>'Cancelled'</code>, anything else → <code>'In progress'</code>.",
        'solution': "SELECT id, CASE WHEN status = 'delivered' THEN 'Delivered' WHEN status = 'cancelled' THEN 'Cancelled' ELSE 'In progress' END FROM orders",
        'check_order': False,
    },
    {
        'id': 65,
        'category': 'CASE WHEN',
        'hint': 'CASE WHEN . WHEN . ELSE',
        'min_tables': 3,
        'description': "Show each product's <b>name</b>, <b>price</b>, and pricing tier: under 30 → <code>'Budget'</code>, 30–100 → <code>'Standard'</code>, over 100 → <code>'Premium'</code>. Name the column <b>price_tier</b>.",
        'solution': "SELECT name, price, CASE WHEN price < 30 THEN 'Budget' WHEN price BETWEEN 30 AND 100 THEN 'Standard' ELSE 'Premium' END AS price_tier FROM products",
        'check_order': False,
    },
    {
        'id': 66,
        'category': 'CASE WHEN',
        'hint': 'CASE WHEN stock = 0',
        'min_tables': 3,
        'description': "Show each product's <b>name</b>, <b>stock</b>, and availability: if <b>stock = 0</b> → <code>'Out of stock'</code>, otherwise → <code>'In stock'</code>. Name the column <b>availability</b>.",
        'solution': "SELECT name, stock, CASE WHEN stock = 0 THEN 'Out of stock' ELSE 'In stock' END AS availability FROM products",
        'check_order': False,
    },
    {
        'id': 67,
        'category': 'CASE WHEN',
        'hint': 'SUM(CASE WHEN)',
        'min_tables': 1,
        'description': "Count <b>active</b> and <b>inactive</b> users in <b>one query</b>. Name the columns <b>active</b> and <b>inactive</b>.",
        'solution': "SELECT SUM(CASE WHEN is_active = 1 THEN 1 ELSE 0 END) AS active, SUM(CASE WHEN is_active = 0 THEN 1 ELSE 0 END) AS inactive FROM users",
        'check_order': False,
    },
    {
        'id': 68,
        'category': 'CASE WHEN',
        'hint': 'CASE WHEN quantity',
        'min_tables': 2,
        'description': "Show each order's <b>id</b>, <b>quantity</b>, and discount label: if quantity ≥ 3 → <code>'10% discount'</code>, otherwise → <code>'No discount'</code>. Name the column <b>discount</b>.",
        'solution': "SELECT id, quantity, CASE WHEN quantity >= 3 THEN '10% discount' ELSE 'No discount' END AS discount FROM orders",
        'check_order': False,
    },
    {
        'id': 69,
        'category': 'CASE WHEN',
        'hint': 'CASE WHEN multi-value',
        'min_tables': 4,
        'description': "Show each return's <b>id</b>, <b>reason</b>, and translated status: <code>'approved'</code> → <code>'Approved'</code>, <code>'rejected'</code> → <code>'Rejected'</code>, otherwise → <code>'Pending'</code>.",
        'solution': "SELECT id, reason, CASE WHEN status = 'approved' THEN 'Approved' WHEN status = 'rejected' THEN 'Rejected' ELSE 'Pending' END FROM returns",
        'check_order': False,
    },
    {
        'id': 70,
        'category': 'CASE WHEN',
        'hint': 'CASE WHEN priority',
        'min_tables': 5,
        'description': "Show each ticket's <b>subject</b> and its priority in full: <code>'low'</code> → <code>'Low'</code>, <code>'medium'</code> → <code>'Medium'</code>, <code>'high'</code> → <code>'High'</code>. Name the column <b>priority_level</b>.",
        'solution': "SELECT subject, CASE WHEN priority = 'low' THEN 'Low' WHEN priority = 'medium' THEN 'Medium' ELSE 'High' END AS priority_level FROM service_requests",
        'check_order': False,
    },

    # =========================================================
    # CATEGORY 8: Subqueries
    # =========================================================
    {
        'id': 71,
        'category': 'Subqueries',
        'hint': 'WHERE > (SELECT AVG)',
        'min_tables': 1,
        'description': "Select all users whose <b>age</b> is <b>above the average</b> age of all users.",
        'solution': 'SELECT * FROM users WHERE age > (SELECT AVG(age) FROM users)',
        'check_order': False,
    },
    {
        'id': 72,
        'category': 'Subqueries',
        'hint': 'WHERE IN (SELECT)',
        'min_tables': 2,
        'description': "Select all users who have made <b>at least one order</b>.",
        'solution': 'SELECT * FROM users WHERE id IN (SELECT DISTINCT user_id FROM orders)',
        'check_order': False,
    },
    {
        'id': 73,
        'category': 'Subqueries',
        'hint': 'WHERE NOT IN (SELECT)',
        'min_tables': 2,
        'description': "Select all users who have <b>never placed an order</b>.",
        'solution': 'SELECT * FROM users WHERE id NOT IN (SELECT DISTINCT user_id FROM orders)',
        'check_order': False,
    },
    {
        'id': 74,
        'category': 'Subqueries',
        'hint': 'WHERE > (SELECT AVG)',
        'min_tables': 2,
        'description': "Select all orders whose <b>total_price</b> is <b>above the average</b> order cost.",
        'solution': 'SELECT * FROM orders WHERE total_price > (SELECT AVG(total_price) FROM orders)',
        'check_order': False,
    },
    {
        'id': 75,
        'category': 'Subqueries',
        'hint': 'WHERE id = (SELECT . LIMIT 1)',
        'min_tables': 2,
        'description': "Select the user who placed the <b>most expensive order</b>.",
        'solution': 'SELECT * FROM users WHERE id = (SELECT user_id FROM orders ORDER BY total_price DESC LIMIT 1)',
        'check_order': False,
    },
    {
        'id': 76,
        'category': 'Subqueries',
        'hint': 'WHERE NOT IN (SELECT)',
        'min_tables': 3,
        'description': "Select the <b>names</b> of products that have <b>never been ordered</b>.",
        'solution': 'SELECT name FROM products WHERE id NOT IN (SELECT DISTINCT product_id FROM orders)',
        'check_order': False,
    },
    {
        'id': 77,
        'category': 'Subqueries',
        'hint': 'COUNT + WHERE IN (SELECT)',
        'min_tables': 2,
        'description': "Count <b>how many users</b> have placed at least one order.",
        'solution': 'SELECT COUNT(*) FROM users WHERE id IN (SELECT DISTINCT user_id FROM orders)',
        'check_order': False,
    },
    {
        'id': 78,
        'category': 'Subqueries',
        'hint': 'WHERE IN (SELECT order_id)',
        'min_tables': 4,
        'description': "Select all orders that have an associated <b>return</b>.",
        'solution': 'SELECT * FROM orders WHERE id IN (SELECT order_id FROM returns)',
        'check_order': False,
    },
    {
        'id': 79,
        'category': 'Subqueries',
        'hint': 'WHERE IN (SELECT WHERE priority)',
        'min_tables': 5,
        'description': "Select users who have a support ticket with <b>high priority</b>.",
        'solution': "SELECT * FROM users WHERE id IN (SELECT user_id FROM service_requests WHERE priority = 'high')",
        'check_order': False,
    },
    {
        'id': 80,
        'category': 'Subqueries',
        'hint': 'Correlated subquery',
        'min_tables': 3,
        'description': "Select products whose <b>price is below the average price in their own category</b>.",
        'solution': 'SELECT * FROM products p WHERE price < (SELECT AVG(price) FROM products WHERE category = p.category)',
        'check_order': False,
    },

    # =========================================================
    # CATEGORY 9: INSERT / UPDATE / DELETE
    # =========================================================
    {
        'id': 81,
        'category': 'INSERT / UPDATE / DELETE',
        'hint': 'INSERT INTO . VALUES',
        'min_tables': 1,
        'needs_reset': True,
        'description': "Add a new user to <b>users</b>:<br><b>name</b> = <code>'Igor Sidorov'</code>, <b>email</b> = <code>'igor@mail.ru'</code>, <b>age</b> = <code>32</code>, <b>city</b> = <code>'Moscow'</code>, <b>is_active</b> = <code>1</code>.",
        'solution': "INSERT INTO users (name, email, age, city, is_active) VALUES ('Igor Sidorov', 'igor@mail.ru', 32, 'Moscow', 1)",
        'check_order': False,
        'verify_query': "SELECT COUNT(*) FROM users WHERE name = 'Igor Sidorov' AND email = 'igor@mail.ru' AND age = 32",
        'verify_expected_count': 1,
    },
    {
        'id': 82,
        'category': 'INSERT / UPDATE / DELETE',
        'hint': 'INSERT INTO . VALUES',
        'min_tables': 3,
        'needs_reset': True,
        'description': "Add a new product to <b>products</b>:<br><b>name</b> = <code>'Smart Watch'</code>, <b>category</b> = <code>'Electronics'</code>, <b>price</b> = <code>299.99</code>, <b>stock</b> = <code>50</code>.",
        'solution': "INSERT INTO products (name, category, price, stock) VALUES ('Smart Watch', 'Electronics', 299.99, 50)",
        'check_order': False,
        'verify_query': "SELECT COUNT(*) FROM products WHERE name = 'Smart Watch' AND price = 299.99",
        'verify_expected_count': 1,
    },
    {
        'id': 83,
        'category': 'INSERT / UPDATE / DELETE',
        'hint': 'INSERT INTO . VALUES',
        'min_tables': 2,
        'needs_reset': True,
        'description': "Add a new order to <b>orders</b>:<br><b>user_id</b> = <code>1</code>, <b>product_id</b> = <code>2</code>, <b>quantity</b> = <code>1</code>, <b>total_price</b> = <code>49.99</code>, <b>status</b> = <code>'pending'</code>, <b>ordered_at</b> = <code>'2024-04-01'</code>.",
        'solution': "INSERT INTO orders (user_id, product_id, quantity, total_price, status, ordered_at) VALUES (1, 2, 1, 49.99, 'pending', '2024-04-01')",
        'check_order': False,
        'verify_query': "SELECT COUNT(*) FROM orders WHERE user_id = 1 AND product_id = 2 AND total_price = 49.99 AND ordered_at = '2024-04-01'",
        'verify_expected_count': 1,
    },
    {
        'id': 84,
        'category': 'INSERT / UPDATE / DELETE',
        'hint': 'UPDATE . SET . WHERE',
        'min_tables': 1,
        'needs_reset': True,
        'description': "Update user with <b>id = 5</b>: set <b>is_active = 0</b>.",
        'solution': 'UPDATE users SET is_active = 0 WHERE id = 5',
        'check_order': False,
        'verify_query': 'SELECT COUNT(*) FROM users WHERE id = 5 AND is_active = 0',
        'verify_expected_count': 1,
    },
    {
        'id': 85,
        'category': 'INSERT / UPDATE / DELETE',
        'hint': 'UPDATE . SET . WHERE',
        'min_tables': 3,
        'needs_reset': True,
        'description': "Reduce the price of all <code>'Books'</code> by <b>10%</b>.",
        'solution': "UPDATE products SET price = ROUND(price * 0.9, 2) WHERE category = 'Books'",
        'check_order': False,
        'verify_query': "SELECT COUNT(*) FROM products WHERE category = 'Books' AND price NOT IN (34.99, 24.99, 44.99)",
        'verify_expected_count': 3,
    },
    {
        'id': 86,
        'category': 'INSERT / UPDATE / DELETE',
        'hint': 'UPDATE . SET . WHERE',
        'min_tables': 2,
        'needs_reset': True,
        'description': "Change the status of order with <b>id = 6</b> to <code>'delivered'</code>.",
        'solution': "UPDATE orders SET status = 'delivered' WHERE id = 6",
        'check_order': False,
        'verify_query': "SELECT COUNT(*) FROM orders WHERE id = 6 AND status = 'delivered'",
        'verify_expected_count': 1,
    },
    {
        'id': 87,
        'category': 'INSERT / UPDATE / DELETE',
        'hint': 'DELETE FROM . WHERE',
        'min_tables': 1,
        'needs_reset': True,
        'description': "Delete the user with <b>id = 10</b> from the <b>users</b> table.",
        'solution': 'DELETE FROM users WHERE id = 10',
        'check_order': False,
        'verify_query': 'SELECT COUNT(*) FROM users WHERE id = 10',
        'verify_expected_count': 0,
    },
    {
        'id': 88,
        'category': 'INSERT / UPDATE / DELETE',
        'hint': 'DELETE FROM . WHERE',
        'min_tables': 2,
        'needs_reset': True,
        'description': "Delete all <b>cancelled orders</b> (<code>status = 'cancelled'</code>) from the <b>orders</b> table.",
        'solution': "DELETE FROM orders WHERE status = 'cancelled'",
        'check_order': False,
        'verify_query': "SELECT COUNT(*) FROM orders WHERE status = 'cancelled'",
        'verify_expected_count': 0,
    },
    {
        'id': 89,
        'category': 'INSERT / UPDATE / DELETE',
        'hint': 'DELETE FROM . WHERE',
        'min_tables': 3,
        'needs_reset': True,
        'description': "Delete all products that are <b>out of stock</b> (<b>stock = 0</b>) from the <b>products</b> table.",
        'solution': 'DELETE FROM products WHERE stock = 0',
        'check_order': False,
        'verify_query': 'SELECT COUNT(*) FROM products WHERE stock = 0',
        'verify_expected_count': 0,
    },
    {
        'id': 90,
        'category': 'INSERT / UPDATE / DELETE',
        'hint': 'DELETE FROM . WHERE',
        'min_tables': 5,
        'needs_reset': True,
        'description': "Delete all support tickets with status <code>'closed'</code> from the <b>service_requests</b> table.",
        'solution': "DELETE FROM service_requests WHERE status = 'closed'",
        'check_order': False,
        'verify_query': "SELECT COUNT(*) FROM service_requests WHERE status = 'closed'",
        'verify_expected_count': 0,
    },

    # =========================================================
    # CATEGORY 10: JOIN — Extended (2 tables: users + orders)
    # =========================================================
    {
        'id': 91,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + COUNT + GROUP BY',
        'min_tables': 2,
        'description': "Show each user's <b>name</b> and the <b>number of orders</b> they placed. Include only users who have placed at least one order.",
        'solution': 'SELECT users.name, COUNT(orders.id) AS order_count FROM users JOIN orders ON users.id = orders.user_id GROUP BY users.id, users.name',
        'check_order': False,
    },
    {
        'id': 92,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + DISTINCT + WHERE',
        'min_tables': 2,
        'description': "Show the <b>name</b> and <b>email</b> of users who have at least one <b>delivered</b> order. No duplicates.",
        'solution': "SELECT DISTINCT users.name, users.email FROM users JOIN orders ON users.id = orders.user_id WHERE orders.status = 'delivered'",
        'check_order': False,
    },
    {
        'id': 93,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + GROUP BY + HAVING',
        'min_tables': 2,
        'description': "Show the <b>name</b> of users and their <b>total spending</b>, but only for users who spent more than <b>150</b> in total.",
        'solution': 'SELECT users.name, SUM(orders.total_price) AS total FROM users JOIN orders ON users.id = orders.user_id GROUP BY users.id, users.name HAVING SUM(orders.total_price) > 150',
        'check_order': False,
    },
    {
        'id': 94,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN + WHERE IS NULL',
        'min_tables': 2,
        'description': "Show the <b>name</b> and <b>city</b> of users who have <b>never placed an order</b>.",
        'solution': 'SELECT users.name, users.city FROM users LEFT JOIN orders ON users.id = orders.user_id WHERE orders.id IS NULL',
        'check_order': False,
    },
    {
        'id': 95,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + MAX + GROUP BY',
        'min_tables': 2,
        'description': "Show each user's <b>name</b> and the amount of their <b>most expensive order</b>.",
        'solution': 'SELECT users.name, MAX(orders.total_price) AS max_order FROM users JOIN orders ON users.id = orders.user_id GROUP BY users.id, users.name',
        'check_order': False,
    },
    {
        'id': 96,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + GROUP BY city',
        'min_tables': 2,
        'description': "Show the <b>city</b> and the <b>total number of orders</b> placed by users from that city. Show only cities with more than <b>2</b> orders.",
        'solution': 'SELECT users.city, COUNT(orders.id) AS order_count FROM users JOIN orders ON users.id = orders.user_id GROUP BY users.city HAVING COUNT(orders.id) > 2',
        'check_order': False,
    },
    {
        'id': 97,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + AVG + GROUP BY + ORDER BY',
        'min_tables': 2,
        'description': "Show each user's <b>name</b> and <b>average order amount</b>, sorted from highest average to lowest.",
        'solution': 'SELECT users.name, AVG(orders.total_price) AS avg_order FROM users JOIN orders ON users.id = orders.user_id GROUP BY users.id, users.name ORDER BY avg_order DESC',
        'check_order': True,
    },
    {
        'id': 98,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + WHERE + ORDER BY',
        'min_tables': 2,
        'description': "Show <b>user name</b>, <b>email</b>, and <b>order status</b> for all orders. Sort by user name ascending.",
        'solution': 'SELECT users.name, users.email, orders.status FROM users JOIN orders ON users.id = orders.user_id ORDER BY users.name ASC',
        'check_order': True,
    },
    {
        'id': 99,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN + COUNT DISTINCT',
        'min_tables': 2,
        'description': "Show every user's <b>name</b> and their <b>order count</b>. Include users with zero orders as well.",
        'solution': 'SELECT users.name, COUNT(orders.id) AS order_count FROM users LEFT JOIN orders ON users.id = orders.user_id GROUP BY users.id, users.name',
        'check_order': False,
    },
    {
        'id': 100,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + SUM + ORDER BY DESC',
        'min_tables': 2,
        'description': "Show each user's <b>name</b> and <b>total spending</b>, sorted from highest spender to lowest.",
        'solution': 'SELECT users.name, SUM(orders.total_price) AS total FROM users JOIN orders ON users.id = orders.user_id GROUP BY users.id, users.name ORDER BY total DESC',
        'check_order': True,
    },

    # =========================================================
    # CATEGORY 10: JOIN — Extended (3 tables: + products)
    # =========================================================
    {
        'id': 101,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 3 + WHERE status',
        'min_tables': 3,
        'description': "Show <b>user name</b>, <b>product name</b>, and <b>order date</b> for all <b>delivered</b> orders.",
        'solution': "SELECT users.name, products.name, orders.ordered_at FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id WHERE orders.status = 'delivered'",
        'check_order': False,
    },
    {
        'id': 102,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + SUM + GROUP BY product',
        'min_tables': 3,
        'description': "Show each <b>product name</b> and the <b>total revenue</b> it generated (sum of all its order amounts).",
        'solution': 'SELECT products.name, SUM(orders.total_price) AS revenue FROM products JOIN orders ON products.id = orders.product_id GROUP BY products.id, products.name',
        'check_order': False,
    },
    {
        'id': 103,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 3 + DISTINCT',
        'min_tables': 3,
        'description': "Show distinct combinations of <b>user name</b> and <b>product category</b> they have ordered from.",
        'solution': 'SELECT DISTINCT users.name, products.category FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id',
        'check_order': False,
    },
    {
        'id': 104,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN + WHERE IS NULL',
        'min_tables': 3,
        'description': "Show the <b>name</b> and <b>price</b> of products that have <b>never been ordered</b>.",
        'solution': 'SELECT products.name, products.price FROM products LEFT JOIN orders ON products.id = orders.product_id WHERE orders.id IS NULL',
        'check_order': False,
    },
    {
        'id': 105,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 3 + WHERE price',
        'min_tables': 3,
        'description': "Show <b>user name</b>, <b>product name</b>, and <b>quantity</b> for orders where the product's price is over <b>50</b>.",
        'solution': 'SELECT users.name, products.name, orders.quantity FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id WHERE products.price > 50',
        'check_order': False,
    },
    {
        'id': 106,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 3 + COUNT DISTINCT',
        'min_tables': 3,
        'description': "Show how many <b>unique products</b> each user has ordered. Display <b>user name</b> and count.",
        'solution': 'SELECT users.name, COUNT(DISTINCT orders.product_id) AS unique_products FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id GROUP BY users.id, users.name',
        'check_order': False,
    },
    {
        'id': 107,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + SUM + GROUP BY category',
        'min_tables': 3,
        'description': "Show each <b>product category</b> and the <b>total amount</b> spent on it across all orders.",
        'solution': 'SELECT products.category, SUM(orders.total_price) AS total_spent FROM products JOIN orders ON products.id = orders.product_id GROUP BY products.category',
        'check_order': False,
    },
    {
        'id': 108,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 3 + WHERE quantity',
        'min_tables': 3,
        'description': "Show <b>user name</b>, <b>product name</b>, and <b>quantity</b> for orders where <b>quantity is 3 or more</b>.",
        'solution': 'SELECT users.name, products.name, orders.quantity FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id WHERE orders.quantity >= 3',
        'check_order': False,
    },
    {
        'id': 109,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN × 2 + GROUP BY',
        'min_tables': 3,
        'description': "Show every user's <b>name</b>, <b>total orders count</b>, and <b>total spending</b>. Include users with zero orders.",
        'solution': 'SELECT users.name, COUNT(orders.id) AS order_count, COALESCE(SUM(orders.total_price), 0) AS total_spent FROM users LEFT JOIN orders ON users.id = orders.user_id GROUP BY users.id, users.name',
        'check_order': False,
    },
    {
        'id': 110,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 3 + MAX + GROUP BY',
        'min_tables': 3,
        'description': "Show each <b>user name</b> and the <b>most expensive product</b> they ever ordered (by product price).",
        'solution': 'SELECT users.name, MAX(products.price) AS max_product_price FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id GROUP BY users.id, users.name',
        'check_order': False,
    },

    # =========================================================
    # CATEGORY 10: JOIN — Extended (4 tables: + returns)
    # =========================================================
    {
        'id': 111,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 3 tables + returns',
        'min_tables': 4,
        'description': "Show <b>user name</b>, <b>order id</b>, and <b>return reason</b> for all returns.",
        'solution': 'SELECT users.name, orders.id, returns.reason FROM users JOIN orders ON users.id = orders.user_id JOIN returns ON orders.id = returns.order_id',
        'check_order': False,
    },
    {
        'id': 112,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN products + orders + returns',
        'min_tables': 4,
        'description': "Show <b>product name</b>, <b>order total price</b>, and <b>return reason</b> for all returned orders.",
        'solution': 'SELECT products.name, orders.total_price, returns.reason FROM products JOIN orders ON products.id = orders.product_id JOIN returns ON orders.id = returns.order_id',
        'check_order': False,
    },
    {
        'id': 113,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 3 + COUNT returns',
        'min_tables': 4,
        'description': "Show <b>user name</b> and the <b>number of returns</b> they have made.",
        'solution': 'SELECT users.name, COUNT(returns.id) AS return_count FROM users JOIN orders ON users.id = orders.user_id JOIN returns ON orders.id = returns.order_id GROUP BY users.id, users.name',
        'check_order': False,
    },
    {
        'id': 114,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + LEFT JOIN returns',
        'min_tables': 4,
        'description': "Show <b>order id</b>, <b>product name</b>, <b>order status</b>, and <b>return status</b>. Include orders with no returns.",
        'solution': 'SELECT orders.id, products.name, orders.status, returns.status FROM orders JOIN products ON orders.product_id = products.id LEFT JOIN returns ON orders.id = returns.order_id',
        'check_order': False,
    },
    {
        'id': 115,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 4 + WHERE approved',
        'min_tables': 4,
        'description': "Show <b>user name</b>, <b>product name</b>, and <b>return reason</b> for returns with status <b>'approved'</b>.",
        'solution': "SELECT users.name, products.name, returns.reason FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id JOIN returns ON orders.id = returns.order_id WHERE returns.status = 'approved'",
        'check_order': False,
    },
    {
        'id': 116,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN × 2 + COUNT returns',
        'min_tables': 4,
        'description': "Show each <b>product name</b> and the <b>total number of times it was returned</b>. Include products with zero returns.",
        'solution': 'SELECT products.name, COUNT(returns.id) AS return_count FROM products LEFT JOIN orders ON products.id = orders.product_id LEFT JOIN returns ON orders.id = returns.order_id GROUP BY products.id, products.name',
        'check_order': False,
    },
    {
        'id': 117,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 4 + GROUP BY',
        'min_tables': 4,
        'description': "Show each <b>return reason</b> and the <b>total value</b> of orders returned for that reason.",
        'solution': 'SELECT returns.reason, SUM(orders.total_price) AS total_value FROM returns JOIN orders ON returns.order_id = orders.id GROUP BY returns.reason',
        'check_order': False,
    },
    {
        'id': 118,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 4 full chain',
        'min_tables': 4,
        'description': "Show <b>user name</b>, <b>product name</b>, <b>order total</b>, and <b>return reason</b> — only for orders from users in <b>'London'</b>.",
        'solution': "SELECT users.name, products.name, orders.total_price, returns.reason FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id JOIN returns ON orders.id = returns.order_id WHERE users.city = 'London'",
        'check_order': False,
    },
    {
        'id': 119,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN × 3 + GROUP BY',
        'min_tables': 4,
        'description': "Show every user's <b>name</b>, <b>order count</b>, and <b>return count</b>. Include users with zero orders and zero returns.",
        'solution': 'SELECT users.name, COUNT(DISTINCT orders.id) AS order_count, COUNT(DISTINCT returns.id) AS return_count FROM users LEFT JOIN orders ON users.id = orders.user_id LEFT JOIN returns ON orders.id = returns.order_id GROUP BY users.id, users.name',
        'check_order': False,
    },
    {
        'id': 120,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 4 + category filter',
        'min_tables': 4,
        'description': "Show <b>product name</b>, <b>category</b>, and the <b>number of times it was returned</b> — only for products in the <b>'Electronics'</b> category.",
        'solution': "SELECT products.name, products.category, COUNT(returns.id) AS return_count FROM products LEFT JOIN orders ON products.id = orders.product_id LEFT JOIN returns ON orders.id = returns.order_id WHERE products.category = 'Electronics' GROUP BY products.id, products.name, products.category",
        'check_order': False,
    },

    # =========================================================
    # CATEGORY 10: JOIN — Extended (5 tables: all)
    # =========================================================
    {
        'id': 121,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 4 + service_requests',
        'min_tables': 5,
        'description': "Show <b>user name</b>, <b>order id</b>, <b>product name</b>, and <b>ticket subject</b> for orders that have a support ticket.",
        'solution': 'SELECT users.name, orders.id, products.name, service_requests.subject FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id JOIN service_requests ON orders.id = service_requests.order_id',
        'check_order': False,
    },
    {
        'id': 122,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + COUNT tickets',
        'min_tables': 5,
        'description': "Show <b>user name</b> and the <b>number of support tickets</b> they have filed.",
        'solution': 'SELECT users.name, COUNT(service_requests.id) AS ticket_count FROM users JOIN service_requests ON users.id = service_requests.user_id GROUP BY users.id, users.name',
        'check_order': False,
    },
    {
        'id': 123,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 5 all tables',
        'min_tables': 5,
        'description': "Show <b>user name</b>, <b>product name</b>, <b>return reason</b>, and <b>ticket subject</b> for orders that have <b>both</b> a return and a support ticket.",
        'solution': 'SELECT users.name, products.name, returns.reason, service_requests.subject FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id JOIN returns ON orders.id = returns.order_id JOIN service_requests ON orders.id = service_requests.order_id',
        'check_order': False,
    },
    {
        'id': 124,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 5 + WHERE high priority',
        'min_tables': 5,
        'description': "Show <b>user name</b>, <b>product name</b>, <b>order status</b>, and <b>ticket priority</b> for <b>high-priority</b> support tickets.",
        'solution': "SELECT users.name, products.name, orders.status, service_requests.priority FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id JOIN service_requests ON orders.id = service_requests.order_id WHERE service_requests.priority = 'high'",
        'check_order': False,
    },
    {
        'id': 125,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN × 4 + GROUP BY',
        'min_tables': 5,
        'description': "Show every user's <b>name</b>, <b>city</b>, <b>order count</b>, and <b>ticket count</b>. Include users with zero orders or tickets.",
        'solution': 'SELECT users.name, users.city, COUNT(DISTINCT orders.id) AS order_count, COUNT(DISTINCT service_requests.id) AS ticket_count FROM users LEFT JOIN orders ON users.id = orders.user_id LEFT JOIN service_requests ON users.id = service_requests.user_id GROUP BY users.id, users.name, users.city',
        'check_order': False,
    },
    {
        'id': 126,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 5 + LEFT JOIN returns',
        'min_tables': 5,
        'description': "Show <b>user name</b>, <b>order id</b>, <b>product name</b>, <b>return reason</b> (if any), and <b>ticket subject</b> (if any) for all orders that have a ticket.",
        'solution': 'SELECT users.name, orders.id, products.name, returns.reason, service_requests.subject FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id JOIN service_requests ON orders.id = service_requests.order_id LEFT JOIN returns ON orders.id = returns.order_id',
        'check_order': False,
    },
    {
        'id': 127,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN + SUM + COUNT + GROUP BY',
        'min_tables': 5,
        'description': "Show each <b>product name</b>, its <b>total revenue</b>, <b>return count</b>, and <b>ticket count</b>.",
        'solution': 'SELECT products.name, SUM(orders.total_price) AS revenue, COUNT(DISTINCT returns.id) AS return_count, COUNT(DISTINCT service_requests.id) AS ticket_count FROM products JOIN orders ON products.id = orders.product_id LEFT JOIN returns ON orders.id = returns.order_id LEFT JOIN service_requests ON orders.id = service_requests.order_id GROUP BY products.id, products.name',
        'check_order': False,
    },
    {
        'id': 128,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'LEFT JOIN × 4 full chain',
        'min_tables': 5,
        'description': "Show <b>user name</b>, <b>order count</b>, <b>return count</b>, and <b>ticket count</b> for every user. Include users with no activity.",
        'solution': 'SELECT users.name, COUNT(DISTINCT orders.id) AS order_count, COUNT(DISTINCT returns.id) AS return_count, COUNT(DISTINCT service_requests.id) AS ticket_count FROM users LEFT JOIN orders ON users.id = orders.user_id LEFT JOIN returns ON orders.id = returns.order_id LEFT JOIN service_requests ON users.id = service_requests.user_id GROUP BY users.id, users.name',
        'check_order': False,
    },
    {
        'id': 129,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 5 + city filter',
        'min_tables': 5,
        'description': "Show <b>user name</b>, <b>product name</b>, and <b>ticket subject</b> for users from <b>'Moscow'</b> who have a support ticket.",
        'solution': "SELECT users.name, products.name, service_requests.subject FROM users JOIN orders ON users.id = orders.user_id JOIN products ON orders.product_id = products.id JOIN service_requests ON orders.id = service_requests.order_id WHERE users.city = 'Moscow'",
        'check_order': False,
    },
    {
        'id': 130,
        'category': 'JOIN / LEFT JOIN',
        'hint': 'JOIN × 5 + ORDER BY + LIMIT',
        'min_tables': 5,
        'description': "Show the <b>top 5 users by total spending</b>: display <b>user name</b>, <b>total spent</b>, and their <b>ticket count</b>.",
        'solution': 'SELECT users.name, SUM(orders.total_price) AS total_spent, COUNT(DISTINCT service_requests.id) AS ticket_count FROM users JOIN orders ON users.id = orders.user_id LEFT JOIN service_requests ON users.id = service_requests.user_id GROUP BY users.id, users.name ORDER BY total_spent DESC LIMIT 5',
        'check_order': True,
    },
]

EXERCISES = {e['id']: e for e in EXERCISES_LIST}


def get_exercises_for_tables(table_count):
    """Return exercises available for the given number of tables, in category order."""
    return [e for e in EXERCISES_LIST if e.get('min_tables', 1) <= table_count]
